version: '3.1'
services: 
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql_task_tracker
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: task_tracker
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
  
  adminer:
    image: adminer
    container_name: adminer_task_tracker
    restart: always
    ports:
      - 8080:8080
volumes:
  db: